### ISSUE TITLE
Where is the p3Net?

### ISSUE THREAD

**Issue by ziskazuo** [LitterMa-820/P3Net#3]
Where is the p3Net? 
![1714630251318](https://github.com/LitterMa-820/PATNet/assets/132803942/0aed83f4-16e6-402a-94c1-736be80412c8)

Do you want to import PANet?

**Comment by ziskazuo** [comment]
And where is the code used for test? Is that prediction.py in Floder eval?

**Comment by ziskazuo** [comment]
Thanks!

**Comment by LitterMa-820** [comment]
> And where is the code used for test? Is that prediction.py in Floder eval?

Yes, prediction.py is used to generate prediction maps, and mae_mF_wF_Sm_Em.py is used to get test metrics.

> And where is the code used for test? Is that prediction.py in Floder eval?

We're sorry that we didn't update the model names while we were cleaning up the code.
