### ISSUE TITLE
p2t_base.pth

### ISSUE THREAD

**Issue by 55-svg** [LitterMa-820/P3Net#4]
The pre-training weight file is called p2t_base.pth, but the name of the weight file you gave is not this, may I ask if I need to find a new weight file with the same name or continue to use the weight file you sent but change the name of the file?

**Comment by LitterMa-820** [comment]
The pre-trained model weights refer to the parameters used by the P2T-Base backbone during training. However, the weights we give are those obtained after a full training process. You need to download p2t_base.pth by yourself.

**Comment by 55-svg** [comment]
fine
