### ISSUE TITLE
数据结果不同

### ISSUE THREAD

**Issue by 55-svg** [LitterMa-820/P3Net#5]
按照您论文的参数跑的代码，效果比论文中差一个多点，请问是您调了参数吗？我如果按照代码中原始的参数跑代码会不会效果和你的一样呢

**Comment by LitterMa-820** [comment]
The model weights we provide for download are trained with the parameters set in the paper and code. Due to the different types of servers used and a certain degree of randomness, there may be some deviations in the results.

**Comment by 55-svg** [comment]
您代码的参数和论文中描述的有些地方不太一致，比如说decay_epoch什么的，请问按照论文跑效果会好一些还是按照您代码上默认的参数跑会好一些，我目前是按照论文参数跑的，存在一些差距

**Comment by LitterMa-820** [comment]
> 您代码的参数和论文中描述的有些地方不太一致，比如说decay_epoch什么的，请问按照论文跑效果会好一些还是按照您代码上默认的参数跑会好一些，我目前是按照论文参数跑的，存在一些差距

We apologize for some problems in the code arrangement, but the implementation effect is consistent with the paper. It is normal for the experimental results to have some deviations. If you need to get the results presented in the paper, just use the model weights we provide.
