### ISSUE TITLE
请问一下评估标准

### ISSUE THREAD

**Issue by 55-svg** [LitterMa-820/P3Net#7]
matlab评估的F和E有三个结果，类似于adpEm:0.949; meanEm:0.968; maxEm:0.974; adpFm:0.911; meanFm:0.919; maxFm:0.939，但是论文中只有Fβ和E3，请问是怎么换算的结果呀

**Comment by LitterMa-820** [comment]
一般采用maxFm 和mean em作为Fβ和E3
